import { addDays, format, getISOWeek, startOfWeek, subDays } from "date-fns";
import { connection } from "next/server";
import ACShell from "@/components/ac/ACShell";
import ACCard from "@/components/ac/ACCard";
import ACSectionHeader from "@/components/ac/ACSectionHeader";
import Eyebrow from "@/components/ac/Eyebrow";
import Ring from "@/components/ac/Ring";
import RegenerateReflectionButton from "@/components/ac/RegenerateReflectionButton";
import { AC, GOAL_RING_COLORS, ringColorForScore } from "@/lib/design-tokens";
import { getWeekStats } from "@/lib/week-stats";
import { prisma } from "@/lib/prisma";

export default async function ReviewPage() {
  await connection();

  const now = new Date();
  const thisWeekStart = startOfWeek(now, { weekStartsOn: 1 });
  const reviewWeekStart = subDays(thisWeekStart, 7);
  const reviewWeekEnd = addDays(reviewWeekStart, 6);

  const [reflection, weekStats] = await Promise.all([
    prisma.weeklyReflection.findUnique({ where: { weekStart: reviewWeekStart } }),
    getWeekStats(reviewWeekEnd),
  ]);

  const goalsBreakdown = reflection
    ? (JSON.parse(reflection.goalsBreakdown) as {
        goalId: number;
        goalText: string;
        tasksCompleted: number;
        tasksTotal: number;
      }[])
    : [];
  const carryForward = reflection
    ? (JSON.parse(reflection.carryForward) as string[])
    : [];

  const score =
    reflection && reflection.tasksTotal > 0
      ? reflection.tasksCompleted / reflection.tasksTotal
      : 0;
  const scorePercent = Math.round(score * 100);

  const dayStats = weekStats.days.map((d) => ({
    label: d.dayLabel,
    value: d.ratio,
    hasData: d.hasData,
  }));

  const isoWeek = getISOWeek(reviewWeekStart);

  const bestDay = dayStats.reduce<{ label: string; value: number } | null>((best, d) => {
    if (!d.hasData) return best;
    if (!best || d.value > best.value) return { label: d.label, value: d.value };
    return best;
  }, null);
  const worstDay = dayStats.reduce<{ label: string; value: number } | null>((worst, d) => {
    if (!d.hasData) return worst;
    if (!worst || d.value < worst.value) return { label: d.label, value: d.value };
    return worst;
  }, null);

  return (
    <ACShell>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          gap: 16,
          marginBottom: 24,
          flexWrap: "wrap",
        }}
      >
        <div>
          <Eyebrow>
            Week {isoWeek} · {format(reviewWeekStart, "MMM d")} – {format(reviewWeekEnd, "MMM d")}
          </Eyebrow>
          <h1
            style={{
              fontSize: 60,
              fontWeight: 800,
              margin: "2px 0 0",
              letterSpacing: "-0.03em",
              lineHeight: 1,
            }}
          >
            Review
          </h1>
          <p style={{ margin: "6px 0 0", color: AC.dim, fontSize: 14 }}>
            {reflection
              ? `Generated by AI · ${reflection.summary.split(/\s+/).length} words`
              : "No reflection generated yet for this week."}
          </p>
        </div>
        <RegenerateReflectionButton label={reflection ? "Regenerate" : "Generate"} />
      </div>

      <ACCard
        style={{
          padding: "28px 32px",
          marginBottom: 18,
          display: "grid",
          gridTemplateColumns: "auto 1fr",
          gap: 32,
          alignItems: "center",
        }}
      >
        <div style={{ position: "relative", width: 220, height: 220, flexShrink: 0 }}>
          <Ring size={220} stroke={20} value={score} color={AC.red} glow />
          <div
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <span
              style={{
                fontSize: 48,
                fontWeight: 800,
                letterSpacing: "-0.03em",
                lineHeight: 1,
                color: AC.text,
              }}
            >
              {scorePercent}
              <span style={{ fontSize: 22, color: AC.dim }}>%</span>
            </span>
            <Eyebrow style={{ fontSize: 11, marginTop: 4 }}>week score</Eyebrow>
            {reflection && (
              <span
                style={{
                  fontSize: 13,
                  color: AC.text,
                  marginTop: 2,
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {reflection.tasksCompleted}/{reflection.tasksTotal}
              </span>
            )}
          </div>
        </div>

        <div>
          <Eyebrow color={AC.orange}>Summary</Eyebrow>
          <p
            style={{
              margin: "8px 0 0",
              fontSize: 17,
              lineHeight: 1.55,
              color: AC.text,
              fontWeight: 400,
            }}
          >
            {reflection?.summary ||
              "Generate a reflection to see the AI summary, goal breakdown, and carry-forward suggestions for the past week."}
          </p>

          {reflection && (
            <div style={{ marginTop: 18, display: "flex", gap: 24, flexWrap: "wrap" }}>
              <Stat
                label="Best day"
                value={bestDay?.label ?? "—"}
                sub={bestDay ? `${Math.round(bestDay.value * 100)}%` : ""}
                color={AC.green}
              />
              <Stat
                label="Worst day"
                value={worstDay?.label ?? "—"}
                sub={worstDay ? `${Math.round(worstDay.value * 100)}%` : ""}
                color={AC.red}
              />
              <Stat
                label="Tasks done"
                value={`${reflection.tasksCompleted}`}
                sub={`of ${reflection.tasksTotal}`}
                color={AC.cyan}
              />
            </div>
          )}
        </div>
      </ACCard>

      <ACSectionHeader label="By day" />
      <ACCard style={{ marginBottom: 22 }}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(7, 1fr)",
            gap: 10,
          }}
        >
          {dayStats.map((s, i) => {
            const color = s.hasData ? ringColorForScore(s.value) : "rgba(255,255,255,0.1)";
            return (
              <div
                key={i}
                style={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  padding: "8px 4px",
                }}
              >
                <Eyebrow style={{ fontSize: 11 }}>{s.label}</Eyebrow>
                <div
                  style={{ position: "relative", width: 64, height: 64, marginTop: 8 }}
                >
                  {s.hasData ? (
                    <Ring size={64} stroke={6} value={s.value} color={color} />
                  ) : (
                    <div
                      style={{
                        width: 64,
                        height: 64,
                        borderRadius: 32,
                        border: "1.5px dashed rgba(255,255,255,0.1)",
                      }}
                    />
                  )}
                  {s.hasData && (
                    <div
                      style={{
                        position: "absolute",
                        inset: 0,
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontSize: 14,
                        fontWeight: 800,
                        color: AC.text,
                      }}
                    >
                      {Math.round(s.value * 100)}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </ACCard>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
          gap: 16,
        }}
      >
        <ACCard>
          <ACSectionHeader
            label="Goals breakdown"
            right={`${goalsBreakdown.length} goal${goalsBreakdown.length === 1 ? "" : "s"}`}
          />
          {goalsBreakdown.length === 0 ? (
            <p style={{ margin: 0, fontSize: 13, color: AC.dim }}>
              No goal data — generate a reflection to populate.
            </p>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {goalsBreakdown.map((g, i) => {
                const v = g.tasksTotal > 0 ? g.tasksCompleted / g.tasksTotal : 0;
                const color = GOAL_RING_COLORS[i % GOAL_RING_COLORS.length];
                return (
                  <div key={g.goalId}>
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "baseline",
                        gap: 12,
                      }}
                    >
                      <p
                        style={{
                          margin: 0,
                          fontSize: 14,
                          color: AC.text,
                          fontWeight: 500,
                          flex: 1,
                          minWidth: 0,
                        }}
                      >
                        {g.goalText}
                      </p>
                      <span
                        style={{
                          fontSize: 12,
                          color: AC.dim,
                          fontVariantNumeric: "tabular-nums",
                          whiteSpace: "nowrap",
                        }}
                      >
                        {g.tasksCompleted}/{g.tasksTotal} · {Math.round(v * 100)}%
                      </span>
                    </div>
                    <div
                      style={{
                        marginTop: 6,
                        height: 6,
                        borderRadius: 3,
                        background: "rgba(255,255,255,0.06)",
                        overflow: "hidden",
                      }}
                    >
                      <div
                        style={{
                          height: "100%",
                          width: `${Math.round(v * 100)}%`,
                          background: color,
                          boxShadow: `0 0 10px ${color}`,
                          transition: "width 600ms cubic-bezier(.4,0,.2,1)",
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </ACCard>

        <ACCard>
          <ACSectionHeader
            label="Carry forward"
            right={`${carryForward.length} item${carryForward.length === 1 ? "" : "s"}`}
          />
          <p
            style={{
              margin: 0,
              fontSize: 13,
              color: AC.dim,
              lineHeight: 1.5,
              marginBottom: 12,
            }}
          >
            These didn&apos;t get done. Pull them into next week&apos;s plan.
          </p>
          {carryForward.length === 0 ? (
            <p style={{ margin: 0, fontSize: 13, color: AC.dim }}>
              Nothing to carry forward.
            </p>
          ) : (
            <ul
              style={{
                listStyle: "none",
                padding: 0,
                margin: 0,
                display: "flex",
                flexDirection: "column",
                gap: 8,
              }}
            >
              {carryForward.map((c, i) => (
                <li
                  key={i}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10,
                    padding: "10px 12px",
                    background: "rgba(255,255,255,0.03)",
                    borderRadius: 12,
                  }}
                >
                  <span
                    style={{
                      width: 6,
                      height: 6,
                      borderRadius: 3,
                      background: AC.orange,
                      boxShadow: `0 0 6px ${AC.orange}`,
                      flexShrink: 0,
                    }}
                  />
                  <span
                    style={{ fontSize: 13, color: AC.text, flex: 1, lineHeight: 1.4 }}
                  >
                    {c}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </ACCard>
      </div>
    </ACShell>
  );
}

interface StatProps {
  label: string;
  value: string;
  sub: string;
  color: string;
}

function Stat({ label, value, sub, color }: StatProps) {
  return (
    <div>
      <Eyebrow style={{ fontSize: 11 }}>{label}</Eyebrow>
      <p
        style={{
          margin: "2px 0 0",
          fontSize: 22,
          fontWeight: 800,
          color,
          letterSpacing: "-0.02em",
        }}
      >
        {value}
      </p>
      <p style={{ margin: 0, fontSize: 11, color: AC.dim }}>{sub}</p>
    </div>
  );
}
